version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      next:
        patterns:
          - "next"
          - "next-*"
          - "eslint-config-next"
          - "@next/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      fumadocs:
        patterns:
          - "fumadocs-*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
